Improved ssh-auth-sock reporting

diff --git a/apkovl/usr/local/bin/ssh-auth-sock b/apkovl/usr/local/bin/ssh-auth-sock
--- a/apkovl/usr/local/bin/ssh-auth-sock
+++ b/apkovl/usr/local/bin/ssh-auth-sock
@@ -6,15 +6,18 @@ latest_auth_sock() {
     -type s \
     -name 'agent.*' \
     -exec ls -1t {} + \
-    | head -1
+    2>/dev/null | head -1
 }
 
 symlink="${HOME}/.ssh/auth_sock"
 
 if [ ! -S "${symlink}" ]; then
+  # Find a valid SSH_AUTH_SOCK socket
   if [ ! -S "${SSH_AUTH_SOCK}" ]; then
     SSH_AUTH_SOCK="$(latest_auth_sock)"
   fi
+
+  # Link to SSH_AUTH_SOCK or clean-up
   if [ -S "${SSH_AUTH_SOCK}" ]; then
     ln -sf "${SSH_AUTH_SOCK}" "${symlink}"
   else
@@ -22,4 +25,9 @@ if [ ! -S "${symlink}" ]; then
   fi
 fi
 
-echo "${symlink} -> $(readlink "${symlink}")"
+# Describe the link or exit
+if [ -S "${symlink}" ]; then
+  echo "${symlink} -> $(readlink "${symlink}")"
+echo
+  echo "SSH Auth Socket not found -- ${symlink}" >&2
+fi
